apiVersion: v1
kind: Secret
metadata:
  name: argo-secret
  namespace: argocd
data:
  github-package: "ZGl0dGhhcGVlbTpnaHBfcURuaGNRMUdqV0hlT2dyaEpaclQ2ekJaa2c3Y2Y4MnBRNk0x"
  .dockerconfigjson: "eyJhdXRocyI6IHsNCiAgICAiZ2hjci5pbyI6IHsNCiAgICAgICJ1c2VybmFtZSI6ICJkaXR0aGFwZWVtIiwNCiAgICAgICJwYXNzd29yZCI6ICJnaHBfcURuaGNRMUdqV0hlT2dyaEpaclQ2ekJaa2c3Y2Y4MnBRNk0xIiwNCiAgICAgICJlbWFpbCI6ICJsYWthZ3VsLnBlZW1AZ21haWwuY29tIn0NCiAgfQ0KfQ=="

---

apiVersion: v1
kind: Secret
metadata:
  name: github-secret
data:
  .dockerconfigjson: "eyJhdXRocyI6IHsNCiAgICAiZ2hjci5pbyI6IHsNCiAgICAgICJ1c2VybmFtZSI6ICJkaXR0aGFwZWVtIiwNCiAgICAgICJwYXNzd29yZCI6ICJnaHBfcURuaGNRMUdqV0hlT2dyaEpaclQ2ekJaa2c3Y2Y4MnBRNk0xIiwNCiAgICAgICJlbWFpbCI6ICJsYWthZ3VsLnBlZW1AZ21haWwuY29tIn0NCiAgfQ0KfQ=="
type: kubernetes.io/dockerconfigjson