# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/ditthapeem/nginx-webserver
  pullPolicy: Always
  tag: latest

imagePullSecrets: 
  - name: github-packages

service:
  type: ClusterIP
  port: 80